Initial commit
umotif-public/terraform-aws-transit-gateway pull request #1
Opened 2021-02-02 12:13 UTC by Ohid25

# Description

An initial step towards creating a module for Transit Gateway.

* Currently only one example of two vpcs in the same region.

2021-02-02 12:51 UTC, marcincuber requested changes

2021-02-02 12:51 UTC, marcincuber commented on README.md
> +  source = "../.."
```
source = "umotif-public/transit-gateway/aws"
version = "~> 1.0.0"
```

2021-02-02 12:51 UTC, marcincuber commented on README.md
> +      vpc_id                                          = "10.0.0.0/16"
fix spacing

2021-02-02 12:51 UTC, marcincuber commented on README.md
> +          destination_cidr_block = module.vpc2.vpc_cidr_block
remove reference to module, should be example vpc cidr

2021-02-02 12:51 UTC, marcincuber commented on README.md
> +          destination_cidr_block = module.vpc1.vpc_cidr_block
remove reference to module, should be example vpc cidr

2021-11-26 16:39 UTC, Ohid25 commented on README.md
> +* [Marcin Cuber](https://github.com/marcincuber) ([LinkedIn](https://www.linkedin.com/in/marcincuber/))
```suggestion
```

2021-11-30 11:14 UTC, Mohammed-afk91 approved these changes

2021-11-30 11:14 UTC, merged